server:
  port: 8100
resilience4j:
#  retry:
#    instances:
#      foo-bar:
#        max-attempts: 5
#        wait-duration: 1s
#        enable-exponential-backoff: true
#  ratelimiter:
#    instances:
#      default:
#        limit-for-period: 2
#        limit-refresh-period: 10s
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: example
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: localhost:2181
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    '[org.apache.zookeeper.ClientCnxn]': WARN